export default Object.freeze({
  CAIRO: "Cairo",
  GIZA: "Giza",
  ALEXANDRIA: "Alexandria",
  MANSOURA: "Mansoura",
  TANTA: "Tanta",
  ISMAILIA: "Ismailia",
  PORT_SAID: "Port Said",
  SUEZ: "Suez",
  BENI_SUEF: "Beni Suef",
  FAYOUM: "Fayoum",
  MINYA: "Minya",
  ASYUT: "Asyut",
  LUXOR: "Luxor",
  ASWAN: "Aswan",
  HURGHADA: "Hurghada",
  SHARM_EL_SHEIKH: "Sharm El Sheikh",
  MARSA_MATRUH: "Marsa Matruh",
  EL_ARISH: "El Arish",
});
